//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FakeBook
{
    using System;
    using System.Collections.Generic;
    
    public partial class Post
    {
        public int ID { get; set; }
        public string Text { get; set; }
        public Nullable<bool> Bold { get; set; }
        public string RandomColor { get; set; }
        public string FriendId { get; set; }
        public string OwnerId { get; set; }
    }
}
